# -*- coding: utf-8 -*-
"""Shopify Stock Data- DV-Week 04

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z1RB-mhRqnrbEXe8ZJbFxG_GdxidUXM_
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("/content/shopify_stock.csv.xls")
print(df.head())

plt.plot(df["date"], df["close"])

plt.xlabel("Date")
plt.ylabel("Closing Price")
plt.title("Shopify Stock Price")

plt.show()