# -*- coding: utf-8 -*-
"""Health care data -Week -06

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10Wdh-lDiyIIt6B-sEXwG1QJNllqJedQ1
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("/content/healthcare_dataset.csv")

df

print(df.head())

print(df.shape)

print(df.describe())

print(df.isnull().sum())

df = df.dropna()

df = df.dropna(subset=["Medical Condition"])
df["Date of Admission"] = pd.to_datetime(df["Date of Admission"])
df["Discharge Date"] = pd.to_datetime(df["Discharge Date"])

df["Urgency"] = df["Admission Type"].map({
    "Emergency": "Emergency",
    "Urgent": "Urgent",
    "Elective": "Elective"
})

df["Stay_Days"] = (
    df["Discharge Date"] - df["Date of Admission"]
).dt.days

print("Billing Statistics:")
print(df["Billing Amount"].describe())

print("\nHospital Stay Statistics:")
print(df["Stay_Days"].describe())

print("\nDemographics:")
print(df.groupby("Medical Condition")["Age"].agg(["count", "mean"]))

print("\nGender Distribution:")
print(pd.crosstab(df["Medical Condition"], df["Gender"]))

billing_data = df.groupby(
    ['Medical Condition', 'Insurance Provider']
)['Billing Amount'].sum().unstack(fill_value=0)

billing_data.plot(
    kind='bar',
    stacked=True,
    figsize=(12, 6)
)

import seaborn as sns
plt.figure(figsize=(12, 6))

sns.violinplot(
    data=df,
    x='Medical Condition',
    y='Billing Amount'
)

plt.title('Billing Amount by Medical Condition and Insurance Provider')
plt.xlabel('Medical Condition')
plt.ylabel('Total Billing Amount')
plt.xticks(rotation=45)
plt.legend(title='Insurance Provider')
plt.tight_layout()
plt.show()

plt.title('Billing Amount Distribution by Medical Condition')
plt.xlabel('Medical Condition')
plt.ylabel('Billing Amount')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

plt.figure(figsize=(12, 6))

sns.violinplot(
    data=df,
    x='Insurance Provider',
    y='Billing Amount'
)

plt.title('Billing Amount Distribution by Insurance Provider')
plt.xlabel('Insurance Provider')
plt.ylabel('Billing Amount')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

plt.figure(figsize=(12, 6))

sns.violinplot(
    data=df,
    x='Insurance Provider',
    y='Billing Amount'
)

plt.title('Billing Amount Distribution by Insurance Provider')
plt.xlabel('Insurance Provider')
plt.ylabel('Billing Amount')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()