# -*- coding: utf-8 -*-
"""Apple Stock Data-DV-Week -03

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QmseQOXnyX_mz5kqlaWPUHN2afkhBvvQ
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plp

df=pd.read_csv("/content/AAPL.csv")
df

print(df.head())

print(df.info)

df = df.dropna()
df = df.drop_duplicates()
df

import numpy as np
import pandas as pd

df = pd.read_excel("AAPL.xlsx")

print(df.head())

print(df.tail())

df.info()

print(df.columns)

print(df.dtypes)

print(df.describe())

df = df.dropna()

df["Date"] = pd.to_datetime(df["Date"])

df = df.sort_values("Date")

print(df.head())

print(df.dtypes)