# -*- coding: utf-8 -*-
"""Health care data -Week -05

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F0_3ep0CXWQeTv2G-A3DyyiElUxPFfxZ
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("/content/healthcare_dataset.csv")

df

print(df.head())

print(df.shape)

print(df.describe())

print(df.isnull().sum())

df = df.dropna()

df = df.dropna(subset=["Medical Condition"])
df["Date of Admission"] = pd.to_datetime(df["Date of Admission"])
df["Discharge Date"] = pd.to_datetime(df["Discharge Date"])

df["Urgency"] = df["Admission Type"].map({
    "Emergency": "Emergency",
    "Urgent": "Urgent",
    "Elective": "Elective"
})

df["Stay_Days"] = (
    df["Discharge Date"] - df["Date of Admission"]
).dt.days

print("Billing Statistics:")
print(df["Billing Amount"].describe())

print("\nHospital Stay Statistics:")
print(df["Stay_Days"].describe())

print("\nDemographics:")
print(df.groupby("Medical Condition")["Age"].agg(["count", "mean"]))

print("\nGender Distribution:")
print(pd.crosstab(df["Medical Condition"], df["Gender"]))

